server {
    listen       8080;
    server_name  msemen.localhost;
    root         /usr/share/nginx/html;
    index        index.html;

    location / {
        expires -1;
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }
}

server {
    listen       8080;
    server_name  analytics.localhost;

    location / {
        proxy_pass         http://matomo:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
