server {
    listen       8080;
    server_name  msemen.localhost;
    root         /usr/share/nginx/html;
    index        index.html;

    location / {
        expires -1;
        try_files $uri $uri/ /index.html;
    }

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }
}
